site_name: CCDEX
#docs_dir: default
nav:
        - Home: index.md
        - Key Technique: KeyTechnique.md
        - Rule and incentive models: RulesAndIncentiveModels.md
        - Business Logic : CCDEX_YP_EN.md
        - Wallet Manual: Wallet_Manual_us_EN.md
#theme: cinder
#theme: mkdocs
theme: readthedocs

copyright: &copy 2018 - 2019 <a href="https://ccdex.top/">CCDEX</a> Foundation. All rights reserved.
